export type Tecnico = {
  tecnicoId: string;
  tecnicoEmail: string;
  tecnicoPhone: string;
  tecnicoUniqueId: string;
  tecnicoLocked: string;
  tecnicoServerName: string;
  tecnico_vpa_id: string;
  tecnico_name: string;
  tecnico_register: string;
  tecnico_password: string;
  tecnico_mac: string;
  tecnico_status: string;
  tecnico_key: string;
  tecnicoApiKeyMobile: string;
  tecnicoApiKeySoftware: string;
  tecnicoKeyPrivate: string;
  tecnicoLevelAccess: string;
  tecnicoToken: string;
  tecnicoDeviceStatus: string;
  tecnicoApiKeyHardware: string;
  tecnicoPermission: string;
  tecnicoAddress: string;
  createdAt: any;
  updatedAt: any;
};
