export type User = {
  userId: string;
  email: string;
  password: string;
  firstname: string;
  lastname: string;
  name: string;
  role: string;
  user_vpa_id: string;
  user_name: string;
  user_password: string;
  user_mac: string;
  user_status: string;
  user_key: string;
  userToken: string;
  user_register: string;
  userChatId: string;
  userDeviceStatus: string;
  userKeyPrivate: string;
  userApiKeyHardware: string;
  createdAt: any;
  updatedAt: any;
};
